# Source: neo4j-standalone/templates/neo4j-loadbalancer.yaml
# Service for applications that need access to neo4j
apiVersion: v1
kind: Service
metadata:
  name: "jan-custom"
  namespace: "jan"
  
spec:
  type: "LoadBalancer"

  externalTrafficPolicy: Local
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 7575
      targetPort: 7474
      name: http
    - protocol: TCP
      port: 7473
      targetPort: 7473
      name: https
    - protocol: TCP
      port: 7688
      targetPort: 7687
      name: tcp-bolt
  selector:
    app: "jan"
    helm.neo4j.com/instance: jan